
server:
  port: 8093
  connection-timeout: 18000000
  servlet:
    session:
      timeout: 30m #30分钟，测试的话时间不能太短，否则不准。m是分钟单位，s是秒的单位，h是小时的单位，不写单位的话默认是毫秒

spring:
  application:
    name: aitest
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/aitest_mini_myperf?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hogwartstest.aitestmini.entity
  configuration:
    mapUnderscoreToCamelCase: true

logging:
  level:
    com.hogwartstest.aitestmini.dao: debug #打印sql


jenkins:
  #Jenkins的baseUrl
  url: http://10.1.1.4:5555/
  #Jenkins的用户名
  username: admin
  #Jenkins的密码
  password: hogwarts
  #测试用例后缀名 如果case为文件时，此处必填
  casesuffix: jmx
  #测试命令
  testcommand: hrun
  #Jenkins回调地址(即平台的baseUrl)
  callbackurl: http://localhost:8093/
