
server:
  port: 8093
  connection-timeout: 18000000
  servlet:
    session:
      timeout: 30m #30分钟，测试的话时间不能太短，否则不准。m是分钟单位，s是秒的单位，h是小时的单位，不写单位的话默认是毫秒

spring:
  application:
    name: aitest
  datasource:
    url: jdbc:mysql://stuq.ceshiren.com:13306/aitest_mini_jmeter?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: hogwarts2020
    password: aitest@hogwarts2020
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hogwartstest.aitestmini.entity
  configuration:
    mapUnderscoreToCamelCase: true

logging:
  level:
    com.hogwartstest.aitestmini.dao: debug #打印sql


map:
  local:
    env: 开发环境

#暂时不配置也可以，因为代码逻辑暂时未用到
jmeter:
  home: /opt/jmeter
  result:
    path: G:/ceba/jmeter_install_dir/demo/
